### ISSUE TITLE
Missing Learn.md file

### ISSUE THREAD

**Issue by debangi29** [growupanand/ConvoForm#247]
# **Add Learn.md file as instructed by Gssoc guidelines**

**Comment by debangi29** [comment]
Please assign me the issue @growupanand under Gssoc'24

**Comment by growupanand** [comment]
can you please share Gssoc gudelines link? thanks

**Comment by debangi29** [comment]
https://www.youtube.com/live/K55HMy7alag?feature=shared

Please check this guide video for Gssoc, from 10:35 
Thank you :)

**Comment by growupanand** [comment]
Okay, I have assigned it to you, but please make sure before working on this you have already used the product and go through the codebase which will help you to do this task.

**Comment by growupanand** [comment]
@debangi29 , can you please share the status?

**Comment by debangi29** [comment]
Actually,  I have made it and removed the unnecessary content that was added, but I wanted to ask you about the video and some extra content added in the Repository you provided

**Comment by growupanand** [comment]
> Actually, I have made it and removed the unnecessary content that was added, but I wanted to ask you about the video and some extra content added in the Repository you provided

Okay you can ask me here or DM me on GSSoC's Discord channel.

**Comment by debangi29** [comment]
Will it be okay if I record a video showing how the convo form works?
(Screen record) @growupanand

**Comment by growupanand** [comment]
Yes, thats even better. Let me know the how you are planning to do this and what are the things you willl cover in the video.

**Comment by debangi29** [comment]
Okay, I am recording a sample video and sending it here? Please check if it is ok, and suggest changes if needed

**Comment by growupanand** [comment]
If you like, we can discuss this over [here](https://github.com/growupanand/ConvoForm/discussions/274) in the discussion form about this Demo video idea.

**Comment by growupanand** [comment]
@debangi29, can you please share the status?
