### ISSUE TITLE
As a submitter, user can see form submission progress

### ISSUE THREAD

**Issue by growupanand** [growupanand/ConvoForm#249]
As a form submitter, I would like to see the submission progress during form submission. For example, we can show a progress bar or any other better way.

We can calculate progress by checking fields with data and null values.

`fieldsData` is returned in `useConvoForm`

https://github.com/growupanand/ConvoForm/blob/04f6d31a912992a5b259c0c25bfbfe18d0de91fd/packages/react/src/hooks/useConvoForm.ts#L143

Its type schema

https://github.com/growupanand/ConvoForm/blob/04f6d31a912992a5b259c0c25bfbfe18d0de91fd/packages/db/src/schema/conversation.ts#L9

**Comment by ShampaShaw** [comment]
assign me this issue under gssoc'24

**Comment by growupanand** [comment]
@ShampaShaw ` gssoc'24` is not a valid label, please check guidelines of GSSoC. I have assigned `gssoc` label which are suggested by them.
