### ISSUE TITLE
Add smooth scrolling in landing page

### ISSUE THREAD

**Issue by TenzDelek** [growupanand/ConvoForm#256]
provide smooth scroll using lenis for better user experience

**Comment by growupanand** [comment]
@TenzDelek assigned to you.

**Comment by growupanand** [comment]
@TenzDelek , can you please share the status? Let me know if you need any help.

**Comment by IdrisGit** [comment]
I have looked at the landing page and didn't get which part of the Landing page the enhancement is for.

can you explain more, I can pick this issue up by the weekend.

**Comment by growupanand** [comment]
@IdrisGit , This enhancement is not needed anymore. But thanks for the notice me, I will close this issue.
