### ISSUE TITLE
the logo on demo page is not redirecting and not clickable

### ISSUE THREAD

**Issue by Latish705** [growupanand/ConvoForm#257]
**Describe the bug**
the logo on demo page should redirect the user to landing page as on other page in website if u click on logo it redirect you to landing page

**Expected behavior**
it should redirect to landing page

**Screenshots**
<img width="1680" alt="image" src="https://github.com/growupanand/ConvoForm/assets/104522651/1976d9e2-8516-48c4-bff5-b303cc13446f">

**Comment by Latish705** [comment]
@growupanand I would like to work on this issue

**Comment by growupanand** [comment]
Hello @Latish705, 
You noticed correctly, but this is not a website logo, it is an organization logo that has created the form. Currently, we don't allow adding custom links in the form in our free plan. In the future, it will be in the premium plan.

**Comment by Latish705** [comment]
@growupanand should I close this issue?

**Comment by growupanand** [comment]
@Latish705 For now you can close this issue, until we have a premium plan in platform.
