### ISSUE TITLE
Stars Update

### ISSUE THREAD

**Issue by n-keerthi-gayathri** [growupanand/ConvoForm#258]
**Describe the bug**
Starred value that shows how many people starred repo in the website is static.

**Expected behavior**
I want to change it into dynamic behavior using web scrapping.

**Comment by n-keerthi-gayathri** [comment]
@growupanand please assign me under GSSOC'24

**Comment by growupanand** [comment]
@n-keerthi-gayathri It is dynamic.

![image](https://github.com/growupanand/ConvoForm/assets/29487686/dc0b8f00-e4cd-4166-a219-b10911ce79aa)
