### ISSUE TITLE
Enhancing the footer 

### ISSUE THREAD

**Issue by Amruta7203** [growupanand/ConvoForm#267]
**Is your feature request related to a problem? Please describe.** 
Enhancing the footer by adding hover effects and aligning the components 

**Describe the solution you'd like** A clear and concise description of what you
want to happen.

**Describe alternatives you've considered** A clear and concise description of
any alternative solutions or features you've considered.

**Additional context** Add any other context or screenshots about the feature
request here.

**Comment by growupanand** [comment]
Its already as expected, thanks for suggestion.
