### ISSUE TITLE
Add "ScrollToTop" Button for User Enhancement 

### ISSUE THREAD

**Issue by codercake** [growupanand/ConvoForm#276]
**Comment:** 
Adding a "ScrollToTop" button can significantly enhance user experience by providing a convenient way for users to quickly navigate back to the top of a webpage without having to manually scroll. 

**Problem Description:**
Users may find it cumbersome to manually scroll back to the top of a webpage, especially on pages with extensive content. 

**Solution Description:**
Implement a "ScrollToTop" button that appears on the screen as the user scrolls down the page. When clicked, the button smoothly scrolls the page back to the top, offering users a convenient and efficient way to navigate.

**Alternatives Considered:**
1. **Browser Functionality:** Some browsers offer built-in functionalities for scrolling to the top of a page with a keyboard shortcut or gesture, but not all users may be familiar with these features or find them intuitive.
2. **Back to Top Link:** A traditional hyperlink at the bottom of the page labeled "Back to Top" could serve a similar purpose, but it might require users to visually locate the link, which can be less convenient than a prominently displayed button.

**Additional Context:**
Consider designing the button to appear once the user scrolls beyond a certain point on the page, ensuring it doesn't obstruct the content unnecessarily. Customization options such as button style, placement, and animation can further enhance the UI.

**Record**

- [x]  I agree to follow this project's Code of Conduct
- [x]  I'm a GSSOC'24 contributor
- [x]  I want to work on this issue

**Comment by growupanand** [comment]
@codercake , On which page you are suggesting this? because right now I don't see any need for it in our webapp.

**Comment by codercake** [comment]
In the landing page. Could be v useful.

**Comment by growupanand** [comment]
@codercake , assigned to you.
