### ISSUE TITLE
[Feat]: Create Issue forms and make the issue options more visually appealing

### ISSUE THREAD

**Issue by TonyStark-47** [growupanand/ConvoForm#281]
### Currently, there is an issue template for this repo, but no issue form which will help users in contributing.

- #### I will add Issue Forms to the respective issues to make it easier for the contributor to raise it.
#### Here is an example of how a Bug Issue Form will look like 👇

![image](https://github.com/apu52/METAVERSE/assets/73957207/4c6889aa-3abf-485d-9c41-09f1f562a0aa)

- and issue templates:

![image](https://github.com/apu52/METAVERSE/assets/73957207/6827e4a8-5382-4376-bbf6-afb9f9731252)

**Comment by TonyStark-47** [comment]
I want to work on this issue. So, kindly assign this issue to me ( GSSOC'24 ).

**Comment by growupanand** [comment]
@TonyStark-47 , Are you planning this in GitHub templates? Do they support those form elements?

**Comment by TonyStark-47** [comment]
@growupanand , Yes inside GitHub template. And yes they support those form elements.

**Comment by growupanand** [comment]
@TonyStark-47 okay, assigned to you.

**Comment by TonyStark-47** [comment]
Hey @growupanand, I have raised a PR #282 related to this issue. Please check it out.

**Comment by growupanand** [comment]
@TonyStark-47 , Thank you so much for your contribution! 🙏 Your help is greatly appreciated. If you could share this project with your community, it would mean a lot. 🌟 Additionally, if you have any suggestions for improvements, please feel free to share. 💡 Looking forward to more collaborations! 🚀.

**Comment by growupanand** [comment]
@TonyStark-47 , One think I forget about in the comment process, we want to comment only if the PR is merged, but if PR is denied or issue is closed without creating any PR we don't want to comment this message.

**Comment by growupanand** [comment]
> @TonyStark-47 , One think I forget about in the comment process, we want to comment only if the PR is merged, but if PR is denied or issue is closed without creating any PR we don't want to comment this message.

You can fix it in this issue - https://github.com/growupanand/ConvoForm/issues/287

**Comment by TonyStark-47** [comment]
I have raised a PR #288 related to this. please check it out.

> > @TonyStark-47 , One think I forget about in the comment process, we want to comment only if the PR is merged, but if PR is denied or issue is closed without creating any PR we don't want to comment this message.
> 
> You can fix it in this issue - #287

@growupanand , I have raised a PR #288 related to this. please check it out.
