### ISSUE TITLE
Docs: 📝 Add issue template for Infrastructure

### ISSUE THREAD

**Issue by growupanand** [growupanand/ConvoForm#287]
### Is there an existing issue for this?

- [X] No, I have searched the existing issues

### Issue Description

I want a new template for creating issue related to the infrastructure work.

### Suggested Change

add new template

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by TonyStark-47** [comment]
@growupanand , I have raised a PR #288 related to this as you mentioned it in #281 . please check it out.

**Comment by growupanand** [comment]
@TonyStark-47, can you please fix workflow errors? They are coming on every PR.

<img width="1691" alt="image" src="https://github.com/growupanand/ConvoForm/assets/29487686/1110aeca-ee5d-40d9-ad55-80da3f8a25e6">
<img width="1679" alt="image" src="https://github.com/growupanand/ConvoForm/assets/29487686/980d051b-ae44-4509-aa96-2ad5ba3eef5d">

**Comment by TonyStark-47** [comment]
Hey @growupanand, check my new PR #299 related to this. It will sure fixes the bugs.

**Comment by growupanand** [comment]
@TonyStark-47, Can we do one thing? Let's merge this PR to your own repo and try to do the testing and if it workds there we can merge it here safely.

**Comment by TonyStark-47** [comment]
@growupanand , I already did it. It works there.

**Comment by growupanand** [comment]
@TonyStark-47, Can you enable issues in your forked repo? So that I can test it myself.

**Comment by TonyStark-47** [comment]
@growupanand, Done, enabled the issue.

**Comment by growupanand** [comment]
https://github.com/growupanand/ConvoForm/pull/299

**Comment by growupanand** [comment]
@TonyStark-47 , Again it is failing.

![image](https://github.com/growupanand/ConvoForm/assets/29487686/a30c3f01-1c02-4d02-91e4-f0b1ad0af859)

![image](https://github.com/growupanand/ConvoForm/assets/29487686/98338743-cf17-4da6-8141-2892f9debcf8)

**Comment by growupanand** [comment]
@TonyStark-47 , I have removed your last PR commit. Please check for edge cases this time.

**Comment by TonyStark-47** [comment]
> @TonyStark-47 , Again it is failing.
> 
> ![image](https://private-user-images.githubusercontent.com/29487686/344200874-a30c3f01-1c02-4d02-91e4-f0b1ad0af859.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NDMwMzcsIm5iZiI6MTcxOTY0MjczNywicGF0aCI6Ii8yOTQ4NzY4Ni8zNDQyMDA4NzQtYTMwYzNmMDEtMWMwMi00ZDAyLTkxZTQtZjBiMWFkMGFmODU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA2MzIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMjMzYjZmZjFkNTBlOWVhNDQ4YjdmYzZlMDJmNjA0OWI2ZjVlNGNmMjYxMzU1YWI0ZjZkMzE5Yjc0ZTJkN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ITB8n5tDdHX_43fz7CI9zYRfRQP3CDx4ALS3m97x65s)
> 
> ![image](https://private-user-images.githubusercontent.com/29487686/344201010-98338743-cf17-4da6-8141-2892f9debcf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NDMwMzcsIm5iZiI6MTcxOTY0MjczNywicGF0aCI6Ii8yOTQ4NzY4Ni8zNDQyMDEwMTAtOTgzMzg3NDMtY2YxNy00ZGE2LTgxNDEtMjg5MmY5ZGViY2Y4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA2MzIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNmVjMTU3Mzk4YzA0M2U1NjQ4NThjNzM3NzEwZWNlMmZmNWE2M2VhNDZmNWYzYTU1ZjAyODJiYjRjNmViZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xjU1wWc6kiuqOCGFIutNnXB7aewF38OjS57RFJb3Dck)

## This happened because you raised an blank issue. So I fixed error related to this and this type of edge cases.

**Comment by TonyStark-47** [comment]
@growupanand , so the recent PR #304 fixes the edge cases bugs. Please check it out.

**Comment by growupanand** [comment]
#304

**Comment by growupanand** [comment]
@TonyStark-47 , This is third time, your workflow giving error. Can you please check this edge case also? You can see other open-source repos for better implementation reference.

Kindly create a new Bug issue for this.

![image](https://github.com/growupanand/ConvoForm/assets/29487686/e14dd4e6-f1ca-47ea-b80e-e9b0c4abdc63)


![image](https://github.com/growupanand/ConvoForm/assets/29487686/de9f203a-9cff-4b20-9bab-ab1e4b57c71b)

**Comment by TonyStark-47** [comment]
@growupanand, here before issue number "#" is not used, then how it's gonna recognise its respective issue number. This is not an edge case. PR raiser must include "#" in their PR.

**Comment by growupanand** [comment]
> @growupanand, here before issue number "#" is not used, then how it's gonna recognise its respective issue number. This is not an edge case. PR raiser must include "#" in their PR.

@TonyStark-47 , You are right, but there is not restriction for that, even anything can be in the PR. Our workflow should not failed, workflow is for improvement and making some manual taks automatic, not for restrictions.
