### ISSUE TITLE
fix: 🐛 Replace twitter with X

### ISSUE THREAD

**Issue by AkhilaSunesh** [growupanand/ConvoForm#292]
### Is there an existing issue for this?

- [X] No, I have searched the existing issues

### Describe the bug

![image](https://github.com/growupanand/ConvoForm/assets/140897461/0de83148-c4a4-4213-8ab0-874afc09ab5b)

### Expected behavior

Location : footer.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by growupanand** [comment]
https://github.com/growupanand/ConvoForm/commit/2830fd6593eab7d6d6dd832e95982a87491944f6
