### ISSUE TITLE
fix: 🐛 Show new form without mannual page reload

### ISSUE THREAD

**Issue by kauxp** [growupanand/ConvoForm#297]
### Is there an existing issue for this?

- [x] No, I have searched the existing issues

### Describe the bug

When a new form is created, it does not appear automatically in the list. The user must reload the page to view the newly made form manually.

### Expected behavior

When a new form is created, it should automatically show up on the forms page without the need for the user to reload the page.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by growupanand** [comment]
@kauxp , assigned to you.

**Comment by growupanand** [comment]
@kauxp any update?
