### ISSUE TITLE
feat: 🚀 As creator, I can fill textbox by selecting an template in the Modal "Generate Form using AI"

### ISSUE THREAD

**Issue by growupanand** [growupanand/ConvoForm#298]
### Is there an existing issue for this?

- [X] No, I have searched the existing issues

### Feature Description

In the modal for "Generate Form using AI", user need to type the description of the form in the text input for generating the Form using AI. We can add some templates buttons or dropdown, by which user can prefill some template text in the text input and then can modify it according to there usecase.

### Use Case

Example: User can select a job application template which will fill the text input with the below text content:
"This is job application form for the role of full stack engineer. We required at least 2 years of work experience."

### Benefits

User don't have to write the whole description of the form from scratch.

### Add ScreenShots

![image](https://github.com/growupanand/ConvoForm/assets/29487686/c2e6b859-f348-412e-808e-6665f15cba79)

### Priority

Low

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by stephin007** [comment]
@growupanand Can you assign me this?

**Comment by stephin007** [comment]
hey @growupanand I am running the `drizzle:apply-migration` but it is getting giving a command failed error, any idea what would i be missing here?

**Comment by growupanand** [comment]
> hey @growupanand I am running the `drizzle:apply-migration` but it is getting giving a command failed error, any idea what would i be missing here?

Can you please share the screenshot or the logs of the error?

**Comment by growupanand** [comment]
@stephin007 any update?

**Comment by stephin007** [comment]
Hey , i totally missed your ping ! I ll get back to you. Apologies for the inconvenience.
