### ISSUE TITLE
🚀[Feat]: Make From editor section resizable in Form editor page

### ISSUE THREAD

**Issue by growupanand** [growupanand/ConvoForm#318]
### Is there an existing issue for this?

- [X] No, I have searched the existing issues

### Feature Description

As a form creator, I may want to resize the editor section width, so I can see the input box easilly with large text in one line.

### Use Case

NA

### Add ScreenShots

![image](https://github.com/user-attachments/assets/bee04b64-c665-426c-9906-c1d60f4c9f81)

### Priority

Low

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Goutamchoudhary907** [comment]
Hey @growupanand  i want to work on this can you describe the feature you want in detail , do you want to resize only input section or whole editor section

**Comment by growupanand** [comment]
@Goutamchoudhary907 , This is not needed anymore as input box support multiline and auto resize height.

**Comment by Goutamchoudhary907** [comment]
Ok
