### ISSUE TITLE
Content of home screen overlaps on hover

### ISSUE THREAD

**Issue by Utsavladia** [growupanand/ConvoForm#343]
### Is there an existing issue for this?

- [X] No, I have searched the existing issues

### Describe the bug

![image](https://github.com/user-attachments/assets/c92e0845-f286-4260-9a55-0bce59dadbb1)

### Expected behavior

It should have proper specing 

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Goutamchoudhary907** [comment]
hey @growupanand i want to work on this plz assign this to me

**Comment by growupanand** [comment]
@Goutamchoudhary907 nice to see you are interested on this bug, but this bug is not exist anymore and I am closing this issue also
