### ISSUE TITLE
Feature section should have hover effect to improve interactiveness

### ISSUE THREAD

**Issue by Utsavladia** [growupanand/ConvoForm#344]
### Is there an existing issue for this?

- [X] No, I have searched the existing issues

### Feature Description

It should have hover effect currently look plain 

### Use Case

It will improve experience

### Add ScreenShots

![image](https://github.com/user-attachments/assets/e858aaf7-3558-4dbb-a932-e038bfd74244)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by growupanand** [comment]
@AdityaGahukar , thanks for review this issue but I am planning to revamp the landing page, hence closing this issue.
