### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by nidhi752** [growupanand/ConvoForm#383]
### Description

Adding a dark mode theme enables users to have a more comfortable viewing experience, especially in low-light conditions or during nighttime use. It reduces eye strain by lowering the overall brightness of the screen and can help minimize blue light exposure, which is known to affect sleep patterns. Additionally, dark mode can also improve the readability of content for those who prefer a lower contrast between the text and the background.

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository
- [X] I want to work on this issue and already read the [Contributing Guidelines](https://github.com/growupanand/ConvoForm/blob/main/CONTRIBUTING.md)

**Comment by growupanand** [comment]
@nidhi752 , assigned to you. Please make sure color should match with design.

**Comment by growupanand** [comment]
@nidhi752 , can you please comment on this already created issue so I will assign it - https://github.com/growupanand/ConvoForm/issues/323

**Comment by rohitja26** [comment]
@growupanand  Please assign this task to me I can help you to make the dark mode version of the website as I have already worked with the context API so this will be very easy to do for me

**Comment by growupanand** [comment]
@rohitja26 assigned to you
