### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by its-Pratik-15** [growupanand/ConvoForm#391]
### Description

it will give the client a nice view during night and it will visually appeling

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository
- [X] I want to work on this issue and already read the [Contributing Guidelines](https://github.com/growupanand/ConvoForm/blob/main/CONTRIBUTING.md)

**Comment by its-Pratik-15** [comment]
if you assign i will add it also add hacktoberfest tag to it

**Comment by growupanand** [comment]
duplicate https://github.com/growupanand/ConvoForm/issues/323
