### ISSUE TITLE
In form editor, After remove a form field I can undo this remove

### ISSUE THREAD

**Issue by growupanand** [growupanand/ConvoForm#56]
when user is editing the form, he want to experiment with different fields, so we can allow him to restore a deleted field.

One approach:
In the form field, there is a remove icon button on the right side. We can replace that icon with the undo icon button. Clicking this undo icon button will restore the field.

**Comment by Hemu21** [comment]
@growupanand  can you please assign this to me.

**Comment by growupanand** [comment]
@Hemu21 assigned to you.

**Comment by Hemu21** [comment]
@growupanand  while I visit localhost:3000 I can't able to see the website. favicon is loaded but body is completely black. can you please tell me what to do?

**Comment by growupanand** [comment]
Have you followed all steps for [local setup](https://github.com/growupanand/ConvoForm#local-setup), If so There should be some error in terminal or in browser.

**Comment by Hemu21** [comment]
@growupanand  I followed it, Localhost runs successfuly. But while visiting Only favicon is loading. title is localhost:3000, and screen is black.

**Comment by Hemu21** [comment]
@growupanand  sorry for inconvience, Problem is with clerk. Now it working. Thank you.

**Comment by growupanand** [comment]
@Hemu21 , can you please share the status?

**Comment by Hemu21** [comment]
@growupanand task is almost completed. But there is only requested changes are there. Currently I had exams. I will update it by sat night or Sunday.

**Comment by growupanand** [comment]
@Hemu21 , Thank you so much for your contribution! 🙏 Your help is greatly appreciated. If you could share this project with your community, it would mean a lot. 🌟 Additionally, if you have any suggestions for improvements, please feel free to share. 💡 Looking forward to more collaborations! 🚀
